<a href="https://colab.research.google.com/github/rahulvansh66/woc4.0-ml-sentiment-analysis-RahulVansh/blob/main/NumPy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

# Part 1: Creating ndarrays

1. Convert the below given list of strings to an int32 NumPy array

In [2]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']

In [15]:
# if string contains float then direct conversion of string to int will give error
# so first we'll convert it into float then int
float_list = np.array(slist, dtype = np.float32)
int_list = np.array(float_list, dtype = np.int32)
int_list

array([   2,    1,    0,    2, 1024], dtype=int32)

2. Create an empty 5x5 NumPy matrix

In [9]:
matrix = np.random.random((5,5))
matrix

array([[0.37138705, 0.68971304, 0.76544634, 0.86200597, 0.808814  ],
       [0.85223833, 0.4815183 , 0.26476636, 0.09282908, 0.93960585],
       [0.11444452, 0.59281895, 0.51848615, 0.95549763, 0.06348225],
       [0.89590224, 0.49844701, 0.0921456 , 0.47613172, 0.82936408],
       [0.73753336, 0.01454728, 0.08187375, 0.65596938, 0.51941195]])

# Part 2: Operations between Arrays and Scalars

3. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [ ]:
sample_output = [1,3,9,27,81]

In [14]:
x = np.geomspace(1, 81, num=5)
x = np.array(x, dtype = np.int32)
x

array([ 1,  3,  9, 27, 81], dtype=int32)

4. Transform each of the element of the below matrix according to the below equation

    if x is an elements in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place



In [32]:
mat = [[1,2,3],[4,5,6]]
mat = np.array(mat)

In [33]:
mat = 1 / ((mat * mat)+1)
mat

array([[0.5       , 0.2       , 0.1       ],
       [0.05882353, 0.03846154, 0.02702703]])

# Part 3: Basic Indexing and Slicing

5. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1, for example

In [38]:
output_sample = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,1,1,0],[0,1,1,1,0],[0,0,0,0,0]])
output_sample

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [42]:
#write your code here
mat = np.zeros((5,5))
mat[1:-1, 1:-1] = np.ones((3,3))
mat

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

6. Given the 3x3x3, 3-dimensional NumPy array

In [70]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

i. Slice this matrix to contain only second and third rows, first and second columns of the given matrix.

In [71]:
sample_output = np.array([[[3,4],[6,7]],[[12,13],[15,16]],[[21,22],[24,25]]])
sample_output

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [72]:
arr1 = arr[: ,1:3, :2]
arr1

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

ii. Output a two dimensional matrix as shown below

In [ ]:
sample_output = np.array([[0,3,6],[9,12,15],[18,21,14]])
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

In [74]:
arr2 = arr[: ,0, :]
arr2

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

# Part 4: Boolean Indexing

7. Given the following array, modify it such that even values stay the same and output contains 0s instead of odd values

In [10]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
sample_output = np.array([[0,0,2],[0,4,0],[6,0,8]])
sample_output

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [13]:
a = arr
a[a%2 !=0] = 0
a

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

# Part 5: Fancy Indexing

8. For the given matrix, use fancy indexing to output a 2d matrix consisting all the even elements of the given matrix

In [32]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
sample_output = np.array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])
sample_output

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [36]:
a = arr
b = a[a%2 ==0]
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

# Part 6: Expressing Conditional Logic as Array Operations



Given two following matrices, use conditional logic to replace all the odd elements of matrix A with even elements of matrix B

In [20]:
A = np.arange(9).reshape((3,3))
B = np.arange(1,10).reshape((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
sample_output = np.array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])
sample_output

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

In [23]:
A[A%2 !=0] = B[B%2 ==0]
A

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

# Part 7: Linear Algebra

Given the following system of equations, solve for x and y using either `numpy.linalg.solve(m1,m2)` or using `inv` and `dot`

2x + 5y = 20

3x + 6y = 12

In [30]:
#write your code here
A = [[ 2,   5],
     [3 ,  6]]

B = [[20],
     [12]]

X = np.linalg.inv(A) @ B

In [31]:
X

array([[-20.],
       [ 12.]])